julien-duponchelle/python-mysql-replication

pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/test_basic.py
We need to handle already dropped tables, because we read the
information out of the information_schema. Therefore we cannot construct
the table map cache ouf of the database.
This isn't the best approach, but I can currently think of an better
one.
=> Prevent invalid table-map-entries to crash the whole app

pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py
It's been painful debugging unittests on DB which doesn't support GTID either because it's MySQL older than 5.6 or because it `gtid_mode` is set to OFF. This should help.
=> skipping GTID tests on DBs not set up to support GTID

pymysqlreplication/binlogstream.py, pymysqlreplication/tests/test_basic.py
The rationale behind this is that as server fails over, the binlog position you've got stored from failed server might no longer be valid on the new one. With MySQL 5.6 you're fine, because you got GTIDs, but if you're using older MySQL there is no way of telling from which log position you should start. Timestamp  helps to _roughly_ know where to start. If your app is capable of dealing with duplicates, that is good enough.
=> Support for skipping the binlog until reaching specified timestamp.

pymysqlreplication/row_event.py, pymysqlreplication/tests/test_basic.py
Partial fix for dropped columns blowing up replication when replaying binlog with past events
Mitigates following error:
```
File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/binlogstream.py", line 262, in fetchone
self.__freeze_schema)
File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/packet.py", line 98, in __init__
freeze_schema = freeze_schema)
File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/row_event.py", line 550, in __init__
column_schema = self.column_schemas[i]
IndexError: list index out of range
```
This is just a superficial patch. It does not address deeper issue at hand, which is that `pymysqlreplication` has no good way of handling `RowEvent`s containing columns which have been dropped prior to `pymsqlreplication` start. The …
=> Partial fix for dropped columns blowing up replication 

pymysqlreplication/column.py, pymysqlreplication/table.py
Making Column attributes into regular object attributes instead of a dictionary.
This makes getting the attribute about 20 times faster.
Rationale behind this is the fact that 15% of time spent on creating and using
`RowsEvent` was spent on `Column.__getattr__`. 
There is more to be optimized, but this one was a low hanging fruit.
=> Column attributes as regular attributes instead of a dict

pymysqlreplication/gtid.py
When a gtid value is incorrect raise the value that we attempted to parse
=> gngtid failed parsing: raise with value

pymysqlreplication/binlogstream.py
Issue https://github.com/noplay/python-mysql-replication/issues/121 for details.
This change helps with PyPy, which does not seem to close the socket automatically on exception, leaving a socket in CLOSE_WAIT for each disconnection until the program is terminated.
=> Explicit close stream connection on exception

pymysqlreplication/gtid.py, pymysqlreplication/tests/test_basic.py
Gtid str representation is built from the str of their gtid, and not their repr
=> Fix GtidSet __str__ representation

pymysqlreplication/binlogstream.py
Since client might want to reconnect, close connection and reset connection status when receiving an EOF packet
(note current code seems to work correctly without this patch :p)
=> Close connection on EOF packet

pymysqlreplication/row_event.py
Python would throw an exception for decoding values of columns in charset "utf8mb4", as there is no such encoding "utf8mb4" in python, but just "utf8".
=> bugfix for decoding values of columns in charset "utf8mb4"

pymysqlreplication/binlogstream.py
Missing update _next_seq_no after write raw packet. 
Error traceback:
```
$ python dump_events.py
Traceback (most recent call last):
File "dump_events.py", line 36, in <module>
main()
File "dump_events.py", line 27, in main
for binlogevent in stream:
File "/data/users/xiezhenye/truck/pymysqlreplication/binlogstream.py", line 244, in fetchone
pkt = self._stream_connection._read_packet()
File "/data/users/xiezhenye/truck/pymysql/connections.py", line 952, in _read_packet
(packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 1 expected 10
```
=> fix: missing update _next_seq_no

pymysqlreplication/binlogstream.py
Allows mysql to disconnect stalled connection upon client reconnection.
=> Support for slave_uuid

pymysqlreplication/gtid.py, pymysqlreplication/tests/test_basic.py
Mysql may return gtid joined by ',\n' separator:
SELECT @@global.gtid_executed
=> gtid: fixup parsing on mysql format

pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py, pymysqlreplication/tests/test_data_type.py
Hi, 
I have done same changes to run test using mysql 5.7. Furthermore some simple test to make mysql configuration a bit more permissive, the name of the binlog is retrieved, so you don't have to set to a fixed one.
=> test run with mysql5.7

.travis.yml, pymysqlreplication/tests/base.py, scripts/install_mysql56.sh, scripts/install_mysql57_on_sandbox.sh, scripts/install_mysql_sandbox.sh
With this patch tests can run on different mysql version (5.6 and 5.7). 
Some note about the patch:
- scripts directory store install script for different mysql version
- moved install instruction from .travis.yml to scripts/install_mysql56.sh
- scripts/install_mysql_sandbox.sh install [mysql_sandbox](http://mysqlsandbox.net/)
- script/install_mysql_57_on_sandbox.sh use mysql-sandbox to install mysql 5.7.12
- the env part define DB enviroment variable that decide on which mysql version test will be run
Travis run every combination from mysql version and python version.
The mysql_sandbox could be used to install other version (maybe 5.5). Using the sandbox is more generic that using the s.o. package manager and we can choice the exact version of mysql instead of the provided. version of …
=> setup travis to run test on multiple mysql version (5.6 and 5.7)

README.md
Otherwise this happens:
```
Traceback (most recent call last):
File "./test.py", line 6, in <module>
stream = BinLogStreamReader(connection_settings = mysql_settings)
TypeError: __init__() missing 1 required positional argument: 'server_id'
```
=> Fix the example: Add required server_id

docs/examples.rst
As I comment in #183 , it's import to add privilege introduction to avoid the misleading output, which also be reported in #116 , #131 and #172 .
=> update doc to indicate privileges the user need

pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/tests/test_basic.py
I ended up debugging a slow startup with pymysqlreplication,
the stream "stucked" for a few seconds before seeing first events coming in.
For that purpose I ended up implementing HeartbeatLogEvent and
documenting observed mysql behavior.
I also implemented the heartbeat feature, which is required for the mysqld
to filter events in gtid mode.
=> Implement Heartbeat

.travis.yml, docs/developement.rst, pymysqlreplication/binlogstream.py, pymysqlreplication/tests/binlogfilereader.py, pymysqlreplication/tests/test_abnormal.py
MySQL generates two RotateEvents when flushing binary logs.  The first
is added to the end of the old binary log.  This RotateEvent has a valid
timestamp.  The second is added to the beginning of the new binary log.
This RotateEvent has a timestamp of 0.
Under some circumstances, e.g., the MySQL server crashes, the first
RotateEvent will not be written to the binary log.  (See the [MySQL
Internals Manual 20.9](https://dev.mysql.com/doc/internals/en/event-data-for-specific-event-types.html).)
Before this change, when instantiating BinLogStreamReader with a
positive skip_to_timestamp argument, the RotateEvents with a timestamp
of 0 were ignored.  This could cause silent corruption of the table_map.
This change ensures that RotateEvents always reset the table_map,
log_pos and log_file …
=> Clear table_map if RotateEvent has timestamp of 0

pymysqlreplication/binlogstream.py
The 'p' format character requires 'bytes' type in python3.
=> Fix struct.pack in ReportSlave

pymysqlreplication/packet.py
This method is missing, but it is being called here: https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/packet.py#L358
This causes the replication to break when there is a 32-bit number in a JSON column.
=> Add implementation of read_int32

pymysqlreplication/row_event.py
**bug description:** in some cases _fetch_one_row will result in some parsing error because of bad data packet read.
the miss read originated while reading datetime(3) rows. in cases where there was an error reading the datetime(3) from the packet the read function will return None and will skip reading the millisecond bytes, this will result in in an indentation of the packet reading, which will result error reading the rest of the packet.
**solution:** now the millisecond bytes will be trimmed in case of an error reading datetime(3) rows.
=> Datetime3 read fails entire packet read

README.md
binlog2sql is a popular binlog parser that could convert raw binlog to sql and could generate flashback sql from raw binlog; Hope this project listed in readme's "Projects using this library" section~
=> add binlog2sql project's introduction to readme

pymysqlreplication/binlogstream.py, pymysqlreplication/exceptions.py
I was able to test by disabling binary logging on my local MySQL instance and running tests.  Certainly open to other suggestions as well. #185
=> Raise an explanatory exception when binary logging is not enabled. (Issue 185)

pymysqlreplication/packet.py, pymysqlreplication/tests/test_data_type.py
The current implementation for reading a JSON string is incorrect and will fail to read strings longer than 127 characters. The test that I added in this branch confirms this. This correct implementation will handle longer strings according to the implementation in mysql-server and the included test passes with it.
=> Add variable length JSON string support

pymysqlreplication/binlogstream.py
From mysql docs https://dev.mysql.com/doc/refman/5.6/en/columns-table.html,
> ORDINAL_POSITION is necessary because you might want to say ORDER BY ORDINAL_POSITION.
> Unlike SHOW, SELECT does not have automatic ordering.
=> fix column order

pymysqlreplication/column.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/test_data_type.py
When an enum value is stored in mysql it represent the index of the value (for type=enum('a','b','c') 1 represent 'a' ext... ) also, 0 represents the empty string. (when a wrong value is inserted to an enum column it will be saved as an empty string)
When the package got an enum type it changed the indexes so ('a', 'b', 'c') will be mapped to (0, 1, 2), and it transformed the values from the bin-log accordingly. So value 1 (which is 'a' in this exemp) will be changed to 0 ect..
If a value 0 was received it will be transformed to -1 which in python will be 'c'.
To solve this i added the empty string by default to an enum column metadata and removed the value transformation so that (0, 1, 2, 3) will be mapped to -> ('', 'a', 'b', 'c')
=> Update enum columns to support correct mysql enum indexing

pymysqlreplication/row_event.py, pymysqlreplication/tests/test_data_type.py
This fixes https://github.com/noplay/python-mysql-replication/issues/288
=> Insert NULL in a boolean column returns no rows #288

pymysqlreplication/binlogstream.py, pymysqlreplication/row_event.py
- `GRANT SELECT <list-of-columns> ON <db>.<table> TO '<user>'@'%';` is possible now
- ORDINAL position of the column is used from `information_schema`.`columns` to figure out the columns to be dropped
- Dropped columns are mapped to `__dropped_col_<incremental-number>__`
=> Support for limited columnar access in source MySQL

pymysqlreplication/packet.py, pymysqlreplication/tests/test_data_type.py
In case of large JSON documents, literal values should be retrieved with
`read_uint32` instead of `read_uint32` to avoid further AssertionError:
```
To compensate for the extra space needed by the redundant length
information, we will make the format allow offset and length fields to
come in two different variants: 2 bytes for documents smaller than
64KB, and 4 bytes to support larger documents.
```
https://dev.mysql.com/worklog/task/?id=8132
=> Fix handling of JSON literal values #226 #298

README.md
There is a small typo in README.md.
Should read `databases` rather than `datebases`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, datebases -> databases

pymysqlreplication/packet.py
This PR fixes a bug when handling inlined ints in "large" JSON documents. When attempting to read these values, the incorrect length was used causing some cascading failures downstream trying to parse the bin logs.
Reading the correct lengths for these data types within large JSON documents resolved the issue. 
This is related to https://github.com/noplay/python-mysql-replication/pull/307
=> Add logic to handle inlined ints in large json documents

pymysqlreplication/row_event.py
I found a trivial typo in [pymysqlreplication/row_event.py:535](https://github.com/noplay/python-mysql-replication/blob/f73e0a1b70b71875d8418c96d5755b8329a45f26/pymysqlreplication/row_event.py#L535-L537)
https://github.com/noplay/python-mysql-replication/blob/f73e0a1b70b71875d8418c96d5755b8329a45f26/pymysqlreplication/row_event.py#L535-L538
'This evenement describe'->'This event describes'
=> Fix typo in pymysqlreplication/row_event.py

pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/binlogfilereader.py
pymysql>=1.0 removed pymysql.util.
https://github.com/PyMySQL/PyMySQL/pull/923
replaced bytes2int, int2byte in py23 compatible manner.
There is #337 that aims to fix the same issue.
Another patch is #346 for int2byte part.
Tested `setup.py test` with docker percona instances as in docs.
=> Add pymysql 1.0 support

pymysqlreplication/gtid.py
I found a trivial typo in [pymysqlreplication/gtid.py:19](https://github.com/noplay/python-mysql-replication/blob/f73e0a1b70b71875d8418c96d5755b8329a45f26/pymysqlreplication/gtid.py#L19)
https://github.com/noplay/python-mysql-replication/blob/f73e0a1b70b71875d8418c96d5755b8329a45f26/pymysqlreplication/gtid.py#L15-L19
'x <= a < b' -> 'a <= x < b'
=> Fix typo in pymysqlreplication/gtid.py

pymysqlreplication/column.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/test_data_objects.py, pymysqlreplication/tests/test_data_type.py
I need to have the same column value on Python as it was selected on MySQL.
However the existing code ignores 'ZEROFILL' attribute.
This PR adds support for 'ZEROFILL' attribute.
1. Search for 'ZEROFILL' in column type
2. Set boolean variable zerofill for column objects
3. Format column values for columns with 'ZEROFILL' attribute
+ Added and passed data type test
=> Support 'ZEROFILL' attribute for numeric datatypes

pymysqlreplication/row_event.py, pymysqlreplication/tests/test_data_type.py
1. minimum value for MySQL TIME datatype:
'-838:59:59.000000' = ADDTIME('-838:00:00', ADDTIME('-00:59:00', '-00:00:59'))
2. appropriate timedelta representation of the same value in Python:
datetime.timedelta(hours=-838, minutes=-59, seconds=-59)
= -1 * datetime.timedelta(hours=838, minutes=59, seconds=59)
'sign' must be multiplied to the entire timedelta,
not just to the 'hours' timedelta as in the existing code.
https://github.com/noplay/python-mysql-replication/blob/3de6ff499f7695a800409341f4f859cac5b724d0/pymysqlreplication/row_event.py#L287-L292
refer to convert_timedelta() in pymysql:
https://github.com/PyMySQL/PyMySQL/blob/fb10477caf21122a89d7f216a0670d49dd2aa5d2/pymysql/converters.py#L219-L227
Datatype tests were modified to test the correct minimum value for TIME datatype.
=> Correct timedelta value for negative MySQL TIME datatype

pymysqlreplication/row_event.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_data_type.py
Since MySQL 8.0.16, partition info has been [added](https://github.com/mysql/mysql-server/commit/e11a540fc559dfbed72ba4ec4677638ac917454f) into extra_data in row event.
Current code is aware of extra_data but doesn't parse it accurately. The program reads `extra_data_length / 8` bytes from packet instead of `extra_data_length - 2` of correct byte-length. This leads the program to **skip parsing of extra_data**.
In some cases errors occur, and in other cases parse result shows incorrect field values as in [issue #354](https://github.com/noplay/python-mysql-replication/issues/354#issue-971136865). (**undefined behavior**) 
below are the modifications made:
1. **Correct byte-length of extra_data** to conform to replication protocol
`extra_data_length / 8` -> `extra_data_length - 2`
* AS-IS: …
=> Fix parsing of row events for MySQL8 partitioned table

pymysqlreplication/tests/test_data_type.py
introduced in commit 30d57fb99995b06eae94589b8cc60c5ab70efba4
=> fix typo in test_data_type

pymysqlreplication/event.py
This PR is a fix for [PR#360](https://github.com/noplay/python-mysql-replication/pull/360)(released in 0.27)
I interpreted `mts_accessed_dbs` as db count in [PR#360](https://github.com/noplay/python-mysql-replication/pull/360) .
However after reproducing kvitek's crash in [Issue#278](https://github.com/noplay/python-mysql-replication/issues/278#issuecomment-1060897201),
I did some more research how the variable is set:
https://github.com/mysql/mysql-server/blob/6846e6b2f72931991cc9fd589dc9946ea2ab58c9/sql/log_event.cc#L3598-L3602
(log_event.h /log_event.cc is responsible for writing low-level binlog,
according to
https://dev.mysql.com/doc/internals/en/source-files-related-to-the-binary-log.html)
Turns out that if the value of the variables equals 254,
the variable is no longer interpreted …
=> Skip db name parsing if mts_accessed_dbs == 254

pymysqlreplication/tests/test_basic.py
Currently the `TestBasicBinLogStreamReader::test_allowed_event_list` test fails,
with the actual number being one more than the expected number.
The reason for that is the recent addition of `MariadbGtidEvent` commit
7fd706d1686da90cdb3991279c764f057e24a1f6.
This commit adapts the expected numbers in the test to reflect that change.
=> Fix test_allowed_event_list, MariadbGtidEvent added

.github/workflows/pytest.yml, docker-compose.yml
To easier find out when changes break the tests.
- Use Python 3.7 for starters, because it's the oldest still-supported CPython
interpreter version. More can be added in a subsequent step.
- Use "docker compose" to run the Percona versions from the dev readme. Different
MySQL implementations (e.g. MariaDB, Oracle, etc.) could be added on top.
- The test suite is skipping `test_no_trailing_rotate_event` because it requires a
different test setup, with access to the binlog files.
- The test suite also skips `test_end_log_pos` for now, because it currently
fails and the best solution wasn't obvious to me, the original author should
have a look.
=> Run tests as GitHub Actions

.github/workflows/pytest.yml, pymysqlreplication/packet.py, pymysqlreplication/tests/test_data_type.py
Without the fix, the included test fails with
```
AssertionError: Result length not requested length:
Expected=2.  Actual=0.  Position: 500079.  Data Length: 500079
```
But I suspect (and have seen) also other errors, depending on specific contents
of the byte stream, e.g. ("Json type $random is not handled").
Int32/UInt32 values in json arrays are encoded inline in the "large" encoding
mode, but they are stored using 4 bytes, not 8.  So the `read_uint64()` calls
are wrong here, `read_uint32()` works. Also the check for `large` in that case
is redundant, as `large` is always True for inlined int32/uint32 values.
Relevant parts in mysql server code are functions `serialize_json_array`,
`should_inline_value` and `insert_offset_or_size` in `sql/json_binary.cc` [1].
I believe this fixes issue …
=> Fix decoding large json arrays

.github/workflows/pytest.yml
Use a matrix strategy to run the test suite with different Python interpreter
versions.
=> Run tests with different Python versions

examples/redis_cache.py
Fix `TypeError: BinLogStreamReader.__init__() missing 1 required positional argument: 'server_id'` in redid cache example.
=> fix: redis cache example

pymysqlreplication/tests/test_basic.py
It's a bit redundant with test about GtidSet but if it makes sense I can add more.
=> Unit testing for GTID/GtidSet

pymysqlreplication/gtid.py
Wanted to avoid some reparsing in `sub`, `add`.
=> Avoid reparsing a Gtid to copy in sub/add

pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py
We discovered that some rows in our mysql db contain incorrectly encoded utf8 strings and when iterating through the binary logs, we see the following error when decoding these values:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 29: invalid continuation byte
```
We'd like to be able to ignore such errors when decoding.
This change introduces a new optional parameter for the `BinLogStreamReader` called `ignore_decode_errors`. When set to True, the malformed data will be ignored.
=> Add support for ignoring string decode errors

pymysqlreplication/tests/base.py
The result value executed through the fechone() function is passed in the form of a tuple, but the syntax to compare isMariaDB function always has an error that returns False because it checks for string type data
* before code block (pymysqlreplication/tests/base.py)
``` 
def isMariaDB(self):
if self.__is_mariaDB is None:
self.__is_mariaDB = "MariaDB" in self.execute("SELECT VERSION()").fetchone()
return self.__is_mariaDB
```
* image
* fixed
Change to see the first element in the tuple lookup list
=> Fix test code - 'isMariaDB'

pymysqlreplication/bitmap.py
There is a minor typo in the annotation for the BitCount function on bitmap.py.
It's trivial, but I'd appreciate it if you could consider it
tot**o**l -> total
=> Fix typo in bitmap.py

docs/developement.rst
I noticed a small typo in the "Tests" section of the Development page. The word "carefull" should be corrected to "careful."
Thank you for considering this fix!
=> Fix typo in development.rst

pymysqlreplication/event.py
Fixed a small typo in event.py.
`acessed` -> `accessed`
=> Fix typo in event.py

pymysqlreplication/event.py
There is a typo in the comment of XAPrepareEvent (contans → contains)
=> Fix typo in XAPrepareEvent comment

pymysqlreplication/row_event.py
This PR addresses a typo found in the row_event.py.
this a dirty hack -> this `is` a dirty hack
=> Fix typo in row_event.py

docker-compose.yml, examples/mariadb_gtid/read_event.py, pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py
- Developed the `MariadbAnnotateRowsEvent` class based on the following document
- Documentation link: [https://mariadb.com/kb/en/annotate_rows_event/](https://mariadb.com/kb/en/annotate_rows_event/)
- [link to the source code](https://github.com/cucuridas/python-mysql-replication/blob/d698c1125cbeda6f461fa113320f2144f3531f1a/pymysqlreplication/event.py#L114-L129)
- Updated the **isMariadb field to check for MariaDB and set the 'mariadb settings'** (`__set_mariadb_settings`) accordingly.
- Previous behavior: Only checked if the `auto_position` field existed for MariaDB detection.
- Updated behavior: Now detects MariaDB even if the `auto_position` field is not specified.
- [[link to the source code]](https://github.com/cucuridas/python-mysql-replication/blob/d698c1125cbeda6f461fa113320f2144 …
=> Developed the Mariadbannotate ros event

pymysqlreplication/binlogstream.py
Issue: #428 (SHOW SLAVE HOSTS was deprecated from  MySQL 8.0.22)
Since the `SHOW SLAVE HOSTS` statement was deprecated from MySQL 8.0.22[1], the MySQL variable `slave_uuid` is also be deprecated.
To ensure version compatibility, both the `replica_uuid` and `slave_uuid` variables will be set to the MySQL Server.
This approach aligns with what was done in go-mysql[2].
It would be prudent to change the name of the `slave_uuid` attribute to `server_uuid`, as it encapsulates the meanings of both `slave_uuid` and `replica_uuid`.
---
[1] [SHOW SLAVE HOSTS | SHOW REPLICAS Statement (MySQL Docs)](https://dev.mysql.com/doc/refman/8.0/en/show-slave-hosts.html)  
[2] [Set slave_uuid and replica_uuid (go-mysql-org/go-mysql)](https://github.com/go-mysql-org/go-mysql/pull/656)
=> 'slave_uuid' was deprecated from  MySQL 8.0.22

pymysqlreplication/event.py, pymysqlreplication/row_event.py, pymysqlreplication/tests/test_basic.py
This PR addresses the use of the `super()` function in the classes. Starting with Python 3, `super()` can be called without arguments in instance methods, automatically determining the class and self. This PR applies this simplification, enhancing the code's readability and maintainability.
- Replaced all occurrences of `super(ClassName, self).__init__` with the simplified `super().__init__` in the classes.
```python
super(ClassName, self).__init__(from_packet, event_size, table_map) ...
```
```python
super().__init__(from_packet, event_size, table_map) ...
```
- **Readability**: The new syntax is cleaner and more in line with modern Python practices.
- **Maintainability**: If the class name changes in the future, there's no need to update the call to `super()`.
Fixed: #432
=> Refactor super() usage in classes

pymysqlreplication/binlogstream.py
issue number #430
When using the `pymysqlreplication` package, there was a recurring issue with the `history list length` value under the following circumstances:
- MySQL version 8.x or higher.
- Continuous execution of DML (Data Manipulation Language) statements.
**This problem led to a gradual slowing down of SELECT queries.**
For detailed information, you can refer to the following reference:
https://minervadb.xyz/troubleshooting-innodb-history-length-with-hung-mysql-transaction/
As a result, I investigated the problem area and made necessary modifications. After making the changes, you were able to compare the performance before and after the fix, using monitoring tools such as Prometheus and MySQL Exporter.
- **Modified code**
```python
def __get_table_information(self, schema, …
```
=> fix - Bug/increase history list length

pymysqlreplication/binlogstream.py
We observed that the `Handler_read_rnd` was continually increasing whenever `__get_table_information` was called upon starting PyMyRepl. The reason was found to be the usage of the `ORDER BY` clause on a non-indexed column within the function.
Since the table entries were empty, and `ORDER BY` was being used on a non-indexed column, this led to an increase in the `Handler_read_rnd`. As a remedy, we removed the `ORDER BY` clause from the SQL query and instead used Python's `sort()` method to sort the results. Since `ORDINAL_POSITION` is auto-incremental, this change will return the same sorted results as the original `ORDER BY` clause, without the associated performance penalty.
Removed the `ORDER BY` clause from the SQL query within `__get_table_information`.
Implemented sorting using …
=> Optimize `Handler_read_rnd` by removing ORDER BY clause

pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/tests/test_basic.py
The developed class represents an event in MariaDB's binlog files that indicates which GTIDs were written in the previous file when a new binlog file is added.
This event enables users to inspect the last recorded GTID in the previous binlog file, which can be used as an attribute such as 'auto_position'.
**Development Content**
- Created the 'MariadbGtidListEvent' event class (Referenced the link below for development)
https://mariadb.com/kb/en/gtid_list_event/
- Added test code for the MariadbGTIDListEventParser class
[[link]- test code](https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/a7199da62730f408a1c06ad9a067f6d051f4d94b/pymysqlreplication/tests/test_basic.py#L1080-L1110)
=> Developed ‘MariadbGtidListEvent‘ class

examples/mariadb_gtid/read_event.py, pymysqlreplication/binlogstream.py, pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py
Rebasing https://github.com/julien-duponchelle/python-mysql-replication/pull/422 on the last version of main
=> Add MariadbBinLogCheckPointEvent

pymysqlreplication/row_event.py
fix: #439  
Here is how the scenario Goes:
1. There is a time difference between the event and the actual state of the database.
2. The actual database is dropped.
3. The python-replication-mysql application receives a table map event.
4. Since there is no cached result for the table_id, it tries to retrieve the database's column schema.
5. There are no column schema results from the database.
6. Packets containing information about the table map event's columns are still present.
7. The application exits the if statement, and the packets remain untouched.
8. Incorrect packets are inserted into the null_bitmask.
```
if self.table_id in table_map:
self.column_schemas = table_map[self.table_id].column_schemas
else:
self.column_schemas = …
```
=> fix read column Info from table map event

pymysqlreplication/event.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/test_basic.py
Query strings in QueryEvents that appear in the binlog stream must not necessarily be utf-8 encoded, but the current implementation handles only utf-8.
This commit adds the `errors="backslashreplace"` kwarg to decode(), to avoid a runtime error and insert \xNN escape sequences for byte sequences that are not valid utf-8. It includes a test that generates a QueryEvent with latin-1 encoding, which fails without the fix.
=> Avoid UnicodeDecodeError for non-utf8 QueryEvents

pymysqlreplication/event.py
- Reviewed the existing docstrings to identify variables that need more detailed descriptions.
- Updated the docstrings to include a concise yet comprehensive description for each identified variable.
I appreciate so much that this project provides nice docs using sphinx.
So, I hope this improvement can attribute to the quality of the docs. Thank you. 
I re-requested this PR after squashing. Thank you.
related Issue: #462
=> docs: modify docstrings in event.py

pymysqlreplication/tests/test_basic.py
[PreviousGtidsEvent was recently added to the codebase](https://github.com/julien-duponchelle/python-mysql-replication/commit/19fe16c572d184089a13b65e891c59c5f948968d), but the corresponding test cases in the TestBasicBinLogStreamReader class were not updated. This has been causing GitHub Actions to fail.
This PR fixes the issue by updating the test_allowed_event_list method in TestBasicBinLogStreamReader to include the correct expected lengths for _allowed_event_list.
Before the fix, the test expected lengths of 23, 22, and 22 for different scenarios. These have been corrected to 24, 23, and 23, respectively, to align with the addition of PreviousGtidsEvent.
=> Fix GitHub Actions Failure by Updating Test Code for PreviousGtidsEvent

CHANGELOG
except : refactor and fix typo
=> 0.44.0 Change log

pymysqlreplication/row_event.py
The following is the code for parsing rows events within the Rows Event. It was observed that the `nbd_info_length` and `nbd_info_format` should each be read as 1-byte values, so they need to be modified to `self.packet.read(2)`.
* as-is
https://github.com/julien-duponchelle/python-mysql-replication/blob/c977dd8dde132acad23511369787bf040f40294b/pymysqlreplication/row_event.py#L65
- The table below is derived from comments in the [MySQL source code](https://github.com/mysql/mysql-server/blob/beb865a960b9a8a16cf999c323e46c5b0c67f21f/libbinlogevents/include/rows_event.h#L772-L814), describing the format of extra data (NDB info):
```bash
+----------+--------------------------------------+
|type_code |        extra_row_ndb_info            |
+--- ------+--------------------------------------+
| …
```
=> Incorrect Parsing of Extra Data(NDB info) in Rows Event

pymysqlreplication/row_event.py
This Pull Request aims to remove the duplicate "Affected columns" output in the `UpdateRowsEvent` class.
The `_dump()` method in both `RowsEvent` and `UpdateRowsEvent` classes includes a print statement for the number of affected columns. The duplicate output appears when using `UpdateRowsEvent`.
- Removed the line `print("Affected columns: %d" % self.number_of_columns)` from the `_dump()` method in the `UpdateRowsEvent` class.
Is there a specific reason for the duplicate "Affected columns" output? I'd appreciate any feedback on this.
=> Remove duplicated Affected columns output in UpdateRowsEvent

README.md
-  python-mysql-replication has its usage of 'MySQL to search engine replication', but there is only one usage that can be found in examples/logstash.
- The logstash thing is also a good usage, but I found it better to have more usage. So, I made py-mysql-elasticsearch-sync, which replicates mysql to elasticsearch using python-mysql-replication(https://github.com/jaehyeonpy/py-mysql-elasticsearch-sync).
- I would appreciate if you could merge this.
=> add py-mysql-elasticsearch-sync to readme, a project using pymyrepl

README.md
This PR updates the README's "Featured" section by adding a new AWS blog post. 
The post details [the use of Amazon RDS, XA transactions, Amazon Kinesis, and AWS Lambda for data replication to Amazon OpenSearch Service.](https://aws.amazon.com/ko/blogs/database/enable-change-data-capture-on-amazon-rds-for-mysql-applications-that-are-using-xa-transactions/)
You can check the source code used in the example [here](https://github.com/aws-samples/change-data-capture-mysql-opensearch/blob/71b656a6e248315c68900e4655c04cc5c29b1a1e/mysql_cdc/mysql_replication_listener.py)
[First Post](https://aws.amazon.com/ko/blogs/database/streaming-changes-in-a-database-with-amazon-kinesis/) : Focuses on real-time MySQL binary log replication via Kinesis.
[Second …
=> Update README Featured Section with AWS Blog on RDS, XA Transactions

docs/conf.py, examples/dump_events.py, examples/logstash/mysql_to_logstash.py, examples/redis_cache.py, pymysqlreplication/_compat.py, pymysqlreplication/binlogstream.py, pymysqlreplication/bitmap.py, pymysqlreplication/column.py, pymysqlreplication/constants/BINLOG.py, pymysqlreplication/constants/FIELD_TYPE.py, pymysqlreplication/constants/__init__.py, pymysqlreplication/event.py, pymysqlreplication/gtid.py, pymysqlreplication/packet.py, pymysqlreplication/row_event.py, pymysqlreplication/table.py, pymysqlreplication/tests/__init__.py, pymysqlreplication/tests/base.py, pymysqlreplication/tests/benchmark.py, pymysqlreplication/tests/test_abnormal.py, pymysqlreplication/tests/test_basic.py, pymysqlreplication/tests/test_data_objects.py, pymysqlreplication/tests/test_data_type.py, setup.py
In this PR, we have removed the compatibility with Python 2 to streamline the code and leverage the features of Python 3 more fully. The specific changes include the following:
- Removed `# -*- coding: utf-8 -*-` from the top of Python files, as Python 3 assumes UTF-8 encoding by default.
- Eliminated conditional imports that checked `sys.version_info` to import different modules or packages based on the Python version.
- Deleted `_compat.py` file which was used to handle string type differences between Python 2 and 3.
1. **Removal of UTF-8 encoding declarations**
Python 3 assumes UTF-8 encoding by default, so it's safe to remove `# -*- coding: utf-8 -*-` declarations from all files.
2. **Unification of imports**
Removed conditional imports that were dependent on the Python version. Now, …
=> Remove Python2 compatibility

pymysqlreplication/event.py, pymysqlreplication/packet.py, pymysqlreplication/tests/test_basic.py, pymysqlreplication/tests/test_data_type.py, pymysqlreplication/util/bytes.py
We're releasing v 0.45 before v 1.0 to fix a json parsing error that mysql 5.7 users are facing.
* bug fix json Parser
* make bytes util
* error fix json array, json object
* add datetime, time parsing add test datetime,decimal,time cases
=> v0.45 bug fix json object and array

pymysqlreplication/row_event.py
resolve #510 
Description
----
Over  pymyrepli 1.0 version 
We got column Information from optional metadata
BUT If Mysql 5.7 Users use over 1.0 version They do not get Column Information.
Mysql 5.7 version does not have binlog_row_metadata variable. so we support 0.45.1 version for mysql 5.7 version
Nevertheless If Mysql 5.7 version use over 1.0 Version, users found only last order column Values.
When we do not know column Information values dictionary key is always null, So overwrite value Object.
```
values[name] = self.__read_values_name(
column,
null_bitmap,
null_bitmap_index,
cols_bitmap,
unsigned,
i,
)
```
Solution
----
To avoid user confusion, it is marked and displayed as UNKNOWN_COL.
=> fix last order column only when DML

pymysqlreplication/event.py
문자열 포매팅 되어 있던 부분을 f-string 포매팅으로 변경하였습니다.
closes #523
=> f-string 포매팅 적용: pymysqlreplication/event.py#L112-L119

pymysqlreplication/binlogstream.py
문자열 포매팅 되어 있던 부분을 f-string 포매팅으로 변경하였습니다.
close #535
=> f-string 포매팅 적용: pymysqlreplication/binlogstream.py#354-355

examples/redis_cache.py
This PR updates lines 30 to 33 in `redis_cache.py`, transitioning from the older `%` format style to the more modern and readable f-string format.
- Updated string formatting on lines 30-33 to utilize Python's f-string syntax.
F-strings offer a more intuitive and clean way to format strings in Python, enhancing both readability and performance. This change ensures that our code in `redis_cache.py` remains consistent with modern Python practices.
Would appreciate a review of this change to ensure it aligns with our coding standards and practices.
Thank you!
=> fix : f-string formatting redis_cache.py

pymysqlreplication/binlogstream.py
closes #536 
I apply f-string formatting
=> fix : f-string formatting binlogstream.py L511

README.md
Updated Changelog 
from https://github.com/noplay/python-mysql-replication/blob/master/CHANGELOG
to https://github.com/noplay/python-mysql-replication/blob/main/CHANGELOG
Updated Examples block
from
```
from pymysqlreplication import BinLogStreamReader
mysql_settings = {'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'passwd': ''}
stream = BinLogStreamReader(connection_settings = mysql_settings, server_id=100)
for binlogevent in stream:
binlogevent.dump()
stream.close()
```
to
```
from pymysqlreplication import BinLogStreamReader
MYSQL_SETTINGS = {"host": "127.0.0.1", "port": 3306, "user": "root", "passwd": ""}
def main():
stream = BinLogStreamReader(
connection_settings=MYSQL_SETTINGS, server_id=3, blocking=True
)
for binlogevent in stream:
binlogevent.dump()
stream.close()
if …
```
=> Updated Examples and Changelog in Readme.md

.github/workflows/pytest.yml, pymysqlreplication/tests/base.py
This pull request addresses [Issue #564](https://github.com/julien-duponchelle/python-mysql-replication/issues/564).
To resolve the failing TestLatin1 test, I have added the line `db["charset"] = charset` to base.py.
As a result of this change, the charset setting now functions correctly in the TestLatin1 test.
https://github.com/julien-duponchelle/python-mysql-replication/blob/1d2c8aba5d96ca4573054e51038d9f62b43da9e9/pymysqlreplication/tests/test_basic.py#L1474-L1476
With this fix in place, I have also re-included the test_query_event_latin1 test in the pytest suite, as it now passes successfully.
=> Add omitted charset setting in base.py

pymysqlreplication/event.py
This PR add logging for situations where CRC32 validation does not pass.
By monitoring these failures, we can ensure data integrity throughout the application.
=> Add error logging for crc32 validation failures.

examples/mysql_to_rabbitmq.py
=> add: send mysql_to_rabbitmq.py

pymysqlreplication/binlogstream.py
I found string format in binlogstream.py.
So I convert to f-string that lines.
=> Fix: Apply f-string binlogstream.py L135:L141

.github/workflows/pytest.yml
pdate PyPy Version from 3.9 to 3.10 in pytest
Description:
This PR addresses the need to update the PyPy version used in our pytest environment from PyPy 3.9 to PyPy 3.10. The update ensures that our testing environment is up-to-date with the latest support and optimizations available in PyPy 3.10.
Changes Proposed:
Updated the GitHub Actions workflow file to specify pypy-3.10 under the python-version matrix for the test job.
Adjusted any code or dependencies as necessary to ensure compatibility with PyPy 3.10.
Benefits:
Ensures the codebase is tested against the latest version of PyPy, which may include performance improvements and bug fixes.
Keeps our testing environment current and in alignment with the latest developments in the PyPy project.
=> Replace pypy3.9 with pypy3.10 in pytest

pymysqlreplication/binlogstream.py, pymysqlreplication/row_event.py
resolve #578 
We initialize the table_map when we create the binlogstreamreader object.
After that, if the binlog is maxsize full, a rotateEvent is fired.
At that point, we empty the table_map because the timestamp is not zero.
Then, when we connect to the next binlogfile, we get a rotateEvent with a timestamp of 0. We don't need to empty the table_map again.
However, when we disconnect from mysql and reconnect, we get a fake rotateEvent with a 0 timestamp.
In this case, we inform the client of error logging and do not initialize the table map.
=> fake rotate event check

pymysqlreplication/event.py, pymysqlreplication/tests/test_event.py
- [X ] I have read and understood the [CONTRIBUTING.md](https://github.com/julien-duponchelle/python-mysql-replication/blob/main/CONTRIBUTING.md) document.
- [ X] I have checked there aren't any other open [Pull Requests](https://github.com/julien-duponchelle/python-mysql-replication/pulls) for the desired changes.
- [ X] This PR resolves an issue [#583].
=> add json feature for  binlogevent

pymysqlreplication/tests/test_basic.py
=> test: test dump method in test_user_var_string_event

setup.py
Since the deprecation of `distutils` (#574), the [`packaging`](https://pypi.org/project/packaging/) package has become a requirement, but was missing from the project’s dependencies.
We noticed this when recently attempting to install [pg_chameleon](https://pgchameleon.org/about/), only to end up facing a `ModuleNotFoundError`, which we traced back to this unsatisfied dependency.
The present Pull Request fixes this by explicitly listing `packaging` as a dependency.
=> Fix missing dependency on `packaging`

pymysqlreplication/binlogstream.py
When running the python profiler on this library, I noticed a pretty intense amount of calls and total time spent in `Version.py`.  Upon investigation, I traced the call to a check that happened once per loop in `fetch_one`.  Taking a clue from https://github.com/julien-duponchelle/python-mysql-replication/pull/363/ (which is more than a year old and sitting), I refactored what had initially been a `@lru_cache` change on my end to just be a static call once and then replaced all if trees that used it with the variable.  I also changed as little as possible in an attempt to get this through.  Below are the cProfiler stats before and after the change.  Tested when parsing through a remote binary log, limited both to 3000 events from the stream reader just to save time, there is a nearly 50% …
=> Optimizing version check to happen once per run

README.md
The mailing list has a low traffic I propose to replace it by Github discussions because it's more accessible to new people.
=> Replace the mailling list by github discussions

pymysqlreplication/binlogstream.py, pymysqlreplication/tests/binlogfilereader.py, pymysqlreplication/tests/test_abnormal.py
This PR fix the log statement in `BinLogStreamReader.fetchone` using `logging.WARN`, which triggers an exception.
I've copied the same logic as the logging statement above, using `logging.log(logging.WARN, <statement>)` to fix this issue.
=> fix log statement for BinLogStreamReader.fetchone

README.md
We recently released a new online schema change tool `sb-osc` as an open source. It uses `python-mysql-replication` for capturing DML events from database, so we'd like to add this to the list in README
cc. @dongwook-chan 
[SB-OSC blog](https://sendbird.com/blog/sb-osc-sendbird-online-schema-change)
=> Add sb-osc to README

pymysqlreplication/event.py
The `HeartbeatLogEvent::dump` method had a typo in the `ident` var name (`indent` was used instead). This caused a crash when dumping out heartbeat events. 
I tested this change manually, but haven't added tests yet. Feel free to suggest a good spot for this test and I'll be happy to take another pass.
=> Bug fix: typo in ident variable name

.github/workflows/lint.yml, .pre-commit-config.yaml, CHANGELOG, pymysqlreplication/binlogstream.py, pyproject.toml, scripts/lint.sh
Related to #620
Update the lint script and configuration files to fix the lint error. And remove black because ruff replace it.
* **scripts/lint.sh**
- Update the `ruff` command to use `ruff check` instead of `ruff`.
- Remove the `black` command.
* **.github/workflows/lint.yml**
- Remove `black` from the `Install dependencies` step.
* **.pre-commit-config.yaml**
- Remove the `black` dependency.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/julien-duponchelle/python-mysql-replication/issues/620?shareId=ba4c5bd5-126a-4013-9d82-b29cf328b6c8).
=> Fix lint error & remove black

pymysqlreplication/binlogstream.py
Fixed the same issue as PR [579](https://github.com/julien-duponchelle/python-mysql-replication/pull/579) did, adding a fix for Mysql versions 5.5, 5.6, 5.7
Resolve issue [578](https://github.com/julien-duponchelle/python-mysql-replication/issues/578) for Mysql versions 5.5, 5.6, 5.7
=> Fixing an issue of initializing table map when fake rotate event catching for Mysql versions 5.5, 5.6, 5.7
