julien-duponchelle/python-mysql-replication

- README.md
Also updates the link to my GitHub profile.
> Fixes a typo in the README.

- pymysqlreplication/row_event.py
- pymysqlreplication/tests/test_data_type.py
Avoid total failure when encountering dates such as 2015-00-21 2015-05-00
> Don't fail on incomplete dates (with 00 as day or month)

- pymysqlreplication/binlogstream.py
This will allow to implement custom transports (tls transport and not mysql own
starttls equivalent)
example usage:
```python
import socket
import pymysql.connections
from pymysql.constants import CLIENT
class TLSConnection(pymysql.connections.Connection):
def __init__(self, *args, **kwargs):
kwargs['defer_connect'] = True
super(TLSConnection, self).__init__(*args, **kwargs)
self.ssl = False
self.client_flag &= ~CLIENT.SSL
sock = socket.create_connection((self.host, self.port), self.connect_timeout)
self.host_info = "socket %s:%d" % (self.host, self.port)
sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
sock = self.ctx.wrap_socket(sock, server_hostname=self.host)
self.connect(sock)
mysql_settings={
'host': '1.2.3.4',
'user': 'acme',
'password': 'hackme',
'port': 3306,
'charset': …
```
> Allow to specify a pymysql wrapper or subclass

- pymysqlreplication/row_event.py
- pymysqlreplication/tests/test_data_type.py
> encode mysql time as python datetime.timedelta

- pymysqlreplication/gtid.py
- pymysqlreplication/tests/test_basic.py
I had to debug a weird replication behaviour. Wireshark was no help to read a COM_BINLOG_DUMP_GTID packet. It would probably help someone else :)
> Decode gtid from network packet

- README.md
> Update README to reflect mysql 5.7 support

- pymysqlreplication/binlogstream.py
- pymysqlreplication/event.py
- pymysqlreplication/packet.py
- pymysqlreplication/row_event.py
- pymysqlreplication/tests/test_basic.py
> Add support for ignored_tables and ignored_schema

- pymysqlreplication/gtid.py
- pymysqlreplication/tests/test_basic.py
Gtid & Set functions
Refactor closer to the spec (no conditional offset, a simpler closed-open interval)
Implement set functions:
set - gtid, set + gtid, gtid in set, ..
> Gtid intervals

- README.md
I saw your tests are running fine with 3.5 and 3.6, so I updated your README file.
> Update README to add 3.5 and 3.6 compatibility

- pymysqlreplication/event.py
> fix formatting of GTIDs under py3

- pymysqlreplication/row_event.py
- pymysqlreplication/tests/test_data_type.py
fix float problem related to fieldtype timestamp, datetime. same issue reported in #231
> fix float problem about time fieldtype

- pymysqlreplication/gtid.py
Hello,
Did some improvement in `Gtid` and `GtidSet` documentation.
I am not an expert in RST nor Python documentation so please let me know if anything need a change! :)
Edit: Did a force push to be coherent and document with `Raises:` not `raise:`
> Documentation of GtidSet and improvement in Gtid

- pymysqlreplication/gtid.py
Add some documentation to Gtid/Gtidset. Most notable contribution documentation in detail of the binary format.
> Documentation of Gtid/GtidSet

- pymysqlreplication/gtid.py
I can also remove it if python 2.7 support is no longer needed.
> Gtid: feature gate __cmp__ since it's python2.

- pymysqlreplication/event.py
There is comment written in Korean.
It might be confusing for other contributors.
> Remove korean comment

- README.md
- This PR aims to augment the README with a "Featured Books" section, highlighting our project's mention in the book “[Data Pipelines Pocket Reference](https://www.oreilly.com/library/view/data-pipelines-pocket/9781492087823/)”, published by O'Reilly. Our project is introduced and used as an example in [Chapter 4: Data Ingestion: Extracting Data](https://www.oreilly.com/library/view/data-pipelines-pocket/9781492087823/ch04.html) as a successful example of replicating binary logs of MySQL data, translating these extracts, and loading them into S3.
- You can check the source code used in the example [here](https://github.com/jamesdensmore/datapipelinesbook/blob/main/ch04/mysql_binlog.py#L1C1-L1C1)
- A new "Featured Books" section has been added to the README. 
- Information about the …
> docs: Update README to add Featured Books

- pymysqlreplication/binlogstream.py
- pymysqlreplication/tests/base.py
I'm here to save our eyes from lower-case-statements.
God bless capitalized statements.
> Capitalize SQL Statements

- README.md
https://aws.amazon.com/blogs/database/streaming-changes-in-a-database-with-amazon-kinesis/
> PyMyRepl is featured on AWS

- README.md
This PR updates the "Featured" section of the README to include a mention of our project being showcased in '[Near Zero Downtime Migration from MySQL to DynamoDB](https://aws.amazon.com/ko/blogs/big-data/near-zero-downtime-migration-from-mysql-to-dynamodb/)' by YongSeong Lee from Amazon Web Services.
We look forward to your feedback and additional suggestions.
> Add Featured Section in README

- pymysqlreplication/packet.py
Please see the commit directly below.
> fix typo of mariadb binlog checkpoint

- pymysqlreplication/binlogstream.py
- pymysqlreplication/row_event.py
> add Logging when fake rotate event occured

- pymysqlreplication/tests/test_basic.py
> Replace texts with String constants

- pymysqlreplication/row_event.py
closes [520](https://github.com/julien-duponchelle/python-mysql-replication/issues/520)
> fix : update unknown variable

- .github/workflows/lint.yml
- .github/workflows/pytest.yml
**Description:**
This pull request introduces the workflow_dispatch event to our GitHub Actions configuration, allowing us to manually trigger the action whenever needed.
**Changes:**
Updated the workflow YAML file to include the workflow_dispatch event.
**Benefits:**
Provides flexibility by letting team members run the action outside the standard automated triggers.
Useful for debugging or ensuring the workflow runs as expected after certain changes.
Please review the changes and let me know if any adjustments are needed.
> Add workflow_dispatch to GitHub Actions

- pymysqlreplication/gtid.py
> fix: f-string formatting gtid.py

- README.md
> update logo in Readme

- .github/workflows/lint.yml
- .github/workflows/pytest.yml
Update syntax to comply with standard YAML practices.
> Fix typo in docker compose yaml file

- pymysqlreplication/binlogstream.py
> deprecate disutils

- pymysqlreplication/tests/test_util_bytes.py
> test: test util/bytes to improve coverage

- README.md
Update ReadMe - MySQL server settings part
> [readme] update MySQL server setting part

- pymysqlreplication/row_event.py
> bug-fix-nonesources f string

- pymysqlreplication/binlogstream.py
> 0.30.1 improve performance

- README.md
Description
============
The project was tested on MariDB 10.6 and Python 3.7 and worked correctly.
The current documentation does not indicate that the project works with MariaDB, so this documentation update will provide
more clarity for other users and hopefully expand the user base.
Testing
=======
1. Install MariaDB 10.6 (any minor revision) and install python-mysql-replication.
2. Run the example script `dump_events.py`
3. Log into the MariaDB database and run the following sample SQL statements
```
CREATE DATABASE test;
use test;
CREATE TABLE test4 (id int NOT NULL AUTO_INCREMENT, data VARCHAR(255), data2 VARCHAR(255), PRIMARY KEY(id));
INSERT INTO test4 (data,data2) VALUES ("Hello", "World");
UPDATE test4 SET data = "World", data2="Hello" WHERE id = 1;
DELETE FROM test4 WHERE id = …
```
> Update README to indicate that the project has been tested on MariaDB 10.6 

- CHANGELOG
- docs/conf.py
- setup.py
* Fix parsing of query field of RowsQueryEvent(#602)
* fix log statement for BinLogStreamReader.fetchone(#608)
> release 1.0.7

- pymysqlreplication/binlogstream.py
This PR resolves an issue #[614].
> add quotes in set slave_uuid
